dev:
  image: kino/conts:fed
  hostname: dev.localdomain
  privileged: true
  dns:
    - 8.8.8.8
  dns_search:
    - localdomain
  ports:
    - "3222"
  volumes:
    - /usr/local/docker:/usr/local/docker-host

devcopy:
  image: kino/conts:fedora
  hostname: devcopy.localdomain
  volumes:
    - /usr/local/docker:/usr/local/docker-host
  command: /usr/local/copy.sh
