dev:
  image: kino/conts:fed22
  hostname: dev.localdomain
  privileged: true
  dns:
    - 8.8.8.8
  dns_search:
    - localdomain
  ports:
    - "127.0.0.1:4222:22"
  volumes:
    - /usr/local/docker:/usr/local/docker-host
    - /home/worker/Dropbox:/home/worker/Dropbox

devcopy:
  image: kino/conts:fed22
  hostname: devcopy.localdomain
  volumes:
    - /usr/local/docker:/usr/local/docker-host
  command: /usr/local/copy.sh

cmuscopy:
  extends:
    service: devcopy
  image: kino/conts:fed22-cmus
  
otp:
  extends:
    service: dev
  image: kino/conts:fed22-otp

otpcopy:
  extends:
    service: devcopy
  image: kino/conts:fed22-otp

ghc:
  extends:
    service: dev
  image: kino/conts:fed22-ghc

ghc-ms:
  extends:
    service: ghc
  image: kino/conts:fed22-ghc-ms
