dev:
  image: kino/conts:raspi
  hostname: dev.localdomain
  privileged: true
  dns:
    - 8.8.8.8
  dns_search:
    - localdomain
  ports:
    - "127.0.0.1:4222:22"
  volumes:
    - /usr/local/docker:/usr/local/docker-host
    - ~/work:/home/worker/work
    - ~/.ssh:/home/worker/.ssh

devcopy:
  image: kino/conts:raspi
  hostname: devcopy.localdomain
  volumes:
    - /usr/local/docker:/usr/local/docker-host
  command: /usr/local/copy.sh

