dev:
  image: kino/conts:deb
  hostname: dev.localdomain
  privileged: true
  dns:
    - 8.8.8.8
  dns_search:
    - localdomain
  ports:
    - "127.0.0.1:4222:22"
  volumes:
    - /usr/local/docker:/usr/local/docker-host

devcopy:
  image: kino/conts:deb
  hostname: devcopy.localdomain
  volumes:
    - /usr/local/docker:/usr/local/docker-host
  command: /usr/local/copy.sh

cmus:
  extends:
    service: devcopy
  image: kino/conts:deb-cmus
  
otp:
  extends:
    service: devcopy
  image: kino/conts:deb-otp

ghc:
  extends:
    service: dev
  image: kino/conts:deb-ghc

ghc-ms:
  extends:
    service: ghc
  image: kino/conts:deb-ghc-ms
