#!/bin/sh
if [ $# -ne 1 ];
then
    echo "usage: $0 <image-name>"
    exit 1
fi

docker run --dns=8.8.8.8 -d -p=3222:22 --name dev -h dev.localdomain \
       -v /usr/local/docker:/usr/local/docker-host \
       $1
