dev:
  image: kino/conts:deb-ghc-ms
  hostname: dev.localdomain
  privileged: true
  dns:
    - 8.8.8.8
  dns_search:
    - localdomain
  ports:
    - "22"
  volumes:
    - /usr/local/docker:/usr/local/docker-host

devcopy:
  image: kino/conts:deb-ghc-ms
  hostname: devcopy.localdomain
  volumes:
    - /usr/local/docker:/usr/local/docker-host
  command: /usr/local/copy.sh
